image:
  file: .gitpod.Dockerfile 

ports:
  - port: 3007
    onOpen: open-browser
    visibility: public
  - port: 4000
    onOpen: open-browser
    visibility: public
  - port: 3006
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - graphql.vscode-graphql
    - yzhang.markdown-all-in-one
    - ms-vscode.vscode-typescript-tslint-plugin
    - hediet.vscode-drawio
    - ms-azuretools.vscode-docker

tasks:
  - init: npm run gitpod-init; docker pull deepf/deeplinks:main; docker run -v $(pwd)/packages/deeplinks:/deeplinks --rm --name links --entrypoint "sh" deepf/deeplinks:main -c "cp -r /snapshots/* /deeplinks/snapshots/"; (cd packages/deeplinks && npm run snapshot:last); npm install -g concurrently;
  - command: (cd packages/deeplinks; if git merge-base --is-ancestor origin/main main; then echo ''; else ( echo 'NEED TO PULL DEEPLINKS!'; git checkout main; git pull; cd ../../; npm run apply-deeplinks); fi) && (cd packages/deepcase; if (git merge-base --is-ancestor origin/main main); then echo ''; else ( echo 'NEED TO PULL DEEPCASE!'; git checkout main; git pull; npm ci); fi) && npm run gitpod-start;
